apiVersion: v1
entries:
  employee:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-10-19T12:41:11.132954+05:30"
    description: A Helm chart for deploying sample employee application.
    digest: 5d3a5560ccad73ceebcfbc989091c44db63a89b62e99ac7e9e632043437e32cd
    name: employee
    type: application
    urls:
    - https://ng-rh.github.io/Springboot_Sample_Employees-List_App/employee/chart/employee-0.1.0.tgz
    version: 0.1.0
generated: "2023-10-19T12:41:11.132488+05:30"
